# SPDX-License-Identifier: MIT

# Only used in https://gitlab.com/fedora/ostree/ci-test
# For tests running in the Fedora infrastructure, see .zuul.yaml and
# https://fedoraproject.org/wiki/Zuul-based-ci

# See: https://gitlab.com/fedora/ostree/buildroot
image: quay.io/fedora-ostree-desktops/buildroot:rawhide

# As those are not official images, we build all available variants.
# We build the images for merge requests, we push and sign them for commits
# pushed to release branches and scheduled pipelines.

variables:
  REGISTRY: "quay.io"
  RELEASE_REPO: "fedora-ostree-desktops"

stages:
  - build
  - merge

mr-silverblue-x86_64:
  stage: build
  script:
    - just compose-image silverblue
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-silverblue-aarch64:
  stage: build
  script:
    - just compose-image silverblue
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-silverblue-x86_64:
  stage: build
  script:
    - just compose-image silverblue
    - just upload-container silverblue x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-silverblue-aarch64:
  stage: build
  script:
    - just compose-image silverblue
    - just upload-container silverblue aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-silverblue:
  stage: merge
  script:
    - just multi-arch-manifest silverblue
  needs:
    - job: "build-silverblue-x86_64"
      artifacts: true
    - job: "build-silverblue-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-kinoite-x86_64:
  stage: build
  script:
    - just compose-image kinoite
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-kinoite-aarch64:
  stage: build
  script:
    - just compose-image kinoite
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-kinoite-x86_64:
  stage: build
  script:
    - just compose-image kinoite
    - just upload-container kinoite x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-kinoite-aarch64:
  stage: build
  script:
    - just compose-image kinoite
    - just upload-container kinoite aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-kinoite:
  stage: merge
  script:
    - just multi-arch-manifest kinoite
  needs:
    - job: "build-kinoite-x86_64"
      artifacts: true
    - job: "build-kinoite-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-kinoite-mobile-x86_64:
  stage: build
  script:
    - just compose-image kinoite-mobile
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-kinoite-mobile-aarch64:
  stage: build
  script:
    - just compose-image kinoite-mobile
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-kinoite-mobile-x86_64:
  stage: build
  script:
    - just compose-image kinoite-mobile
    - just upload-container kinoite-mobile x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-kinoite-mobile-aarch64:
  stage: build
  script:
    - just compose-image kinoite-mobile
    - just upload-container kinoite-mobile aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-kinoite-mobile:
  stage: merge
  script:
    - just multi-arch-manifest kinoite-mobile
  needs:
    - job: "build-kinoite-mobile-x86_64"
      artifacts: true
    - job: "build-kinoite-mobile-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-kinoite-nightly-x86_64:
  stage: build
  script:
    - just compose-image kinoite-nightly
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-kinoite-nightly-aarch64:
  stage: build
  script:
    - just compose-image kinoite-nightly
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-kinoite-nightly-x86_64:
  stage: build
  script:
    - just compose-image kinoite-nightly
    - just upload-container kinoite-nightly x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-kinoite-nightly-aarch64:
  stage: build
  script:
    - just compose-image kinoite-nightly
    - just upload-container kinoite-nightly aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-kinoite-nightly:
  stage: merge
  script:
    - just multi-arch-manifest kinoite-nightly
  needs:
    - job: "build-kinoite-nightly-x86_64"
      artifacts: true
    - job: "build-kinoite-nightly-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-sway-atomic-x86_64:
  stage: build
  script:
    - just compose-image sway-atomic
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-sway-atomic-aarch64:
  stage: build
  script:
    - just compose-image sway-atomic
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-sway-atomic-x86_64:
  stage: build
  script:
    - just compose-image sway-atomic
    - just upload-container sway-atomic x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-sway-atomic-aarch64:
  stage: build
  script:
    - just compose-image sway-atomic
    - just upload-container sway-atomic aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-sway-atomic:
  stage: merge
  script:
    - just multi-arch-manifest sway-atomic
  needs:
    - job: "build-sway-atomic-x86_64"
      artifacts: true
    - job: "build-sway-atomic-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-budgie-atomic-x86_64:
  stage: build
  script:
    - just compose-image budgie-atomic
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-budgie-atomic-aarch64:
  stage: build
  script:
    - just compose-image budgie-atomic
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-budgie-atomic-x86_64:
  stage: build
  script:
    - just compose-image budgie-atomic
    - just upload-container budgie-atomic x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-budgie-atomic-aarch64:
  stage: build
  script:
    - just compose-image budgie-atomic
    - just upload-container budgie-atomic aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-budgie-atomic:
  stage: merge
  script:
    - just multi-arch-manifest budgie-atomic
  needs:
    - job: "build-budgie-atomic-x86_64"
      artifacts: true
    - job: "build-budgie-atomic-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-base-atomic-x86_64:
  stage: build
  script:
    - just compose-image base-atomic
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-base-atomic-aarch64:
  stage: build
  script:
    - just compose-image base-atomic
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-base-atomic-x86_64:
  stage: build
  script:
    - just compose-image base-atomic
    - just upload-container base-atomic x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-base-atomic-aarch64:
  stage: build
  script:
    - just compose-image base-atomic
    - just upload-container base-atomic aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-base-atomic:
  stage: merge
  script:
    - just multi-arch-manifest base-atomic
  needs:
    - job: "build-base-atomic-x86_64"
      artifacts: true
    - job: "build-base-atomic-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")

mr-cosmic-atomic-x86_64:
  stage: build
  script:
    - just compose-image cosmic-atomic
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

mr-cosmic-atomic-aarch64:
  stage: build
  script:
    - just compose-image cosmic-atomic
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-cosmic-atomic-x86_64:
  stage: build
  script:
    - just compose-image cosmic-atomic
    - just upload-container cosmic-atomic x86_64
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

build-cosmic-atomic-aarch64:
  stage: build
  script:
    - just compose-image cosmic-atomic
    - just upload-container cosmic-atomic aarch64
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  artifacts:
    paths:
      - .buildid
    expire_in: 1 week

merge-cosmic-atomic:
  stage: merge
  script:
    - just multi-arch-manifest cosmic-atomic
  needs:
    - job: "build-cosmic-atomic-x86_64"
      artifacts: true
    - job: "build-cosmic-atomic-aarch64"
      artifacts: true
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
